### ISSUE TITLE
Skeleton keypoints numbers

### ISSUE THREAD

**Issue by LlamaSi** [ChrisWu1997/2D-Motion-Retargeting#11]
Hi Chris, 
Great work!
May I ask why you just used 15 keypoints and removed the other 10 in Openpose. For example, can we extract the left/right eye/ear information from the Mixamo fbx?

Thanks!

**Comment by ChrisWu1997** [comment]
Thanks:)

The reason is that 15 keypoints is the most basic and stable representation and every character in Mixamo fbx contains these 15 keypoints. For other joint like eye/toe, if you check the Mixamo website, you will find some character in the collection have no such joints while some of them do, which leads to inconsistency. 

Actually, we do have the version of more joints, including fingers, toes, eyes, ears. However, it is done at the cost of removing some characters and applying some heuristic approximations for the missing joints. So we only release the 15 joints version, which is the most stable one.

**Comment by LlamaSi** [comment]
That's reasonable. Thanks for the reply!
