### ISSUE TITLE
Visualization of raw data

### ISSUE THREAD

**Issue by annopackage** [ChrisWu1997/2D-Motion-Retargeting#25]
Hi, the work is really amazing.

The data you provide is coordinates of character, could you provide the raw data of mixamo? I can hardly open the mixamo website at present. Or could provide other resources where we can make our own synthetic data? 

Thanks in advance.

**Comment by ChrisWu1997** [comment]
Thanks for taking interest in our work. 

Unfortunately, currently I'm not able to provide the raw data of Mixamo since it's too large (fbx format). Also, I not sure whether there are other resources where paired data is available. Hope you can figure out a way to open mixamo website successfully :)
