### ISSUE TITLE
Transfer of motions to other characters

### ISSUE THREAD

**Issue by RahhulDd** [ChrisWu1997/2D-Motion-Retargeting#28]
Hello Chris,

I found the project really brilliant and I am trying to implement something similar with motions performed with different affective states like Sad, Angry etc. I have one question regarding training step, when I try to train the network it finds some of the path in the directory to be non-existing. For example, suppose Char1 has 15 number of motion files whereas Char2 has 20 motion files. Train step loads Char2 with Motion number 2.npy from Char1 and Char1 with Motion number 19.npy. For the latter, there exists no Motion number 19.npy. How to solve this issue?

**Comment by ChrisWu1997** [comment]
Hi,

Thanks for taking interest in our work. Unfortunately, I think this work could not handle the case that you described since it's essentially a supervised method which requires the ground truth output. For unsupervised motion transfer, which does not require the ground truth output, I know this work: https://github.com/yzhq97/transmomo.pytorch. Hope that could help you.
