### ISSUE TITLE
About mean pose

### ISSUE THREAD

**Issue by Zhangkunyao** [ChrisWu1997/2D-Motion-Retargeting#8]
Hi, I noticed code written in predict.py.
'''
 mean_pose, std_pose = get_meanpose(config)
...
preprocess_motion2d(input3, mean_pose, std_pose)
'''
I was wondering,when I test my own video,should I also get those data first?

**Comment by ChrisWu1997** [comment]
Yes. `mean_pose` and `std_pose` are always needed since we normalize the input by subtracting the mean and dividing the std:
```python
(motion - mean_pose[:, :, np.newaxis]) / std_pose[:, :, np.newaxis]
```
But note the `mean_pose` and `std_pose` are from the training data, which is already included in the folder [mixamo_data](https://github.com/ChrisWu1997/2D-Motion-Retargeting/tree/master/mixamo_data). So basically you don't need to do anything else except supplying the input motion.

**Comment by QUTGXX** [comment]
@ChrisWu1997 If I want to train the network based on my own dataset and using different nums of key points, how to get the mean pose and std_pose?
